services:
  - type: web
    name: py2java-translator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.web_app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    plan: free 